# Generated by Django 5.2.1 on 2025-05-15 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("time", models.DateTimeField(blank=True, null=True, verbose_name="Время")),
                ("name", models.CharField(max_length=100, verbose_name="Действие")),
                ("is_pleasant_habit", models.BooleanField(verbose_name="Признак полезной привычки")),
                ("recurrence_days", models.PositiveIntegerField(default=1, verbose_name="Периодичность в днях")),
                ("reward", models.CharField(blank=True, max_length=100, null=True, verbose_name="Вознаграждение")),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на выполнение в минутах"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
