# Generated by Django 5.2.1 on 2025-05-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant_habit",
            field=models.BooleanField(verbose_name="Признак приятной привычки"),
        ),
    ]
