# Generated by Django 5.2.1 on 2025-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_is_pleasant_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="notified",
            field=models.BooleanField(default=False, verbose_name="Уведомление отправлено"),
        ),
    ]
